### ISSUE TITLE
Compiling a specific binary in this package

### ISSUE THREAD

**Issue by alxpettit** [coreutils/coreutils#13]
I want to use this code as a basis for my project. I am forking the `mv` command, since it's relatively simple (~500 lines of dedicated code), and its functions closely match the purpose of my program.

(In case you're curious, I'm making a trash program similar to `trash-cli`.)

I tried doing `make help` and `./configure --help`, but I found no option to simply compile one binary.

I did a trace on the Makefile, and isolated the command that produces the `mv` binary:
`gcc  -I. -I./lib  -Ilib -I./lib -Isrc -I./src    -g -O2 -MT src/mv.o -MD -MP -MF $depbase.Tpo -c -o src/mv.o src/mv.c &&\
echo "  CCLD    " src/mv;gcc   -g -O2 -Wl,--as-needed  -o src/mv src/mv.o src/remove.o src/copy.o src/cp-hash.o src/extent-scan.o src/force-link.o src/selinux.o src/libver.a lib/libcoreutils.a  lib/libcoreutils.a    -lacl -lattr `

Of course, it doesn't work without all the object files already generated. I can't tell which lines are producing them, and after skimming the Makefile and configure.ac, I've concluded that I have a newfound appreciation for docker build environments. (I'm mostly a Python programmer, and don't have too much experience with the in-depth GNU toolchains.)

Unfortunately, I can't figure out how to compile it without, y'know, compiling everything else. I don't want to have to drag 50M of source code around just for a variation on a coreutils binary. How can I compile just `mv.c?

**Comment by agordon** [comment]
Hello,

Technical questions about coreutils are better asked by sending an email to coreutils@gnu.org .
I replied to your issue there, please see:
https://lists.gnu.org/archive/html/coreutils/2017-11/msg00006.html

regards,
 - assaf

**Comment by crabdancing** [comment]
@agordon Sent you a response, and never got a response back. Should I CC the mailing list server? I don't know what the mailing list conventions are for GNU. Doesn't seem like we need to involve other participants for such a simple thing.

Also, side note: I know how programming works. I was talking about _dedicated_ code. The code specific to `mv.c`, as opposed to shared code that is abstracted away. A single Python program expands to like 500 system calls. Is there some better language I should use to describe code at a specific abstraction layer?

**Comment by agordon** [comment]
@alxpettit yes, it is best to always CC coreutils@gnu.org - this is how the mailing lists works. If you omit the CC, your message is private.

Regarding "involving other participants" - on the contrary. It is *always* better to keep such discussions public, and allow more people to read and even respond. Keeping them public also ensures they are archives and kept for future reference.

Any further correspondence - please send directly to coreutils@gnu.org (no need to CC individual maintainers).

**Comment by crabdancing** [comment]
@agordon Alrighty! I just thought my questions were fairly irrelevant, but maybe they'll be of use to someone. I'll resend it. :)
