### ISSUE TITLE
How to build from archive source?

### ISSUE THREAD

**Issue by abdulbadii** [coreutils/coreutils#17]
> If you obtained this file as part of a "git clone", then see the
> README-hacking file.  If this file came to you as part of a tar archive,
> then see the file INSTALL for compilation and installation instructions...

got from tar archive but without file INSTALL,
where is the INSTALL ?

**Comment by pixelb** [comment]
The INSTALL file is there. Note distribution archives are available at:
https://ftp.gnu.org/pub/gnu/coreutils/

**Comment by PatMyron** [comment]
https://github.com/coreutils/gnulib/blob/master/doc/INSTALL

CC https://github.com/coreutils/coreutils/issues/9
