### ISSUE TITLE
Error building core Utils 8.15 

### ISSUE THREAD

**Issue by dreyes15** [coreutils/coreutils#18]
I am currently truing to build coreutils 8.15 however I am getting the following error
![Screen Shot 2019-03-10 at 4 05 34 PM](https://user-images.githubusercontent.com/5712088/54092162-660aba80-434e-11e9-9179-ad346a03f88e.png)

When running the config I get the following 
![Screen Shot 2019-03-10 at 4 04 04 PM](https://user-images.githubusercontent.com/5712088/54092133-22b04c00-434e-11e9-955b-2b87607082c9.png)

Anyone know of any fix for this?

**Comment by pixelb** [comment]
That version was released over 7 years ago.
You didn't mention where you're building, or why this version.
You could remove this warning line to get over the issue I'm guessing.
Anyway closing this, since it's not focused on current development

**Comment by dreyes15** [comment]
My mistake I am trying to build it on an Ubuntu 18.04 LTS virtual machine, for the purpose of using a diversification tool to reproduce the results from a paper published in 2015
