### ISSUE TITLE
Repo cannot be cloned

### ISSUE THREAD

**Issue by Midar** [coreutils/coreutils#20]
error: object a6727941433ee1c91a20ede6cb381af1d18c566d: missingSpaceBeforeDate: invalid author/committer line - missing space before date

**Comment by Midar** [comment]
Cloning https://git.savannah.gnu.org/git/coreutils.git however works, so this seems to be an issue with the mirror.

**Comment by avindra** [comment]
@Midar what git version are you using? works for me

```
 $ git clone git@github.com:coreutils/coreutils.git
Cloning into 'coreutils'...
remote: Enumerating objects: 3, done.
remote: Counting objects: 100% (3/3), done.
remote: Compressing objects: 100% (3/3), done.
remote: Total 174257 (delta 0), reused 1 (delta 0), pack-reused 174254
Receiving objects: 100% (174257/174257), 38.31 MiB | 1.79 MiB/s, done.
Resolving deltas: 100% (132786/132786), done.

 $ ls
coreutils
 
 $ git --version
git version 2.21.0
```

**Comment by fweimer** [comment]
The tag object lags a date:

```
object 55b9df1653168e9bd00a9e9a4afad701e0218d54
type commit
tag COREUTILS-4_5_1
tagger Jim Meyering <jim@meyering.net>
```

By default, Git ignores such errors while cloning. See [`transfer.fsckObjects`](https://git-scm.com/docs/git-config#Documentation/git-config.txt-transferfsckObjects) for details.

**Comment by Midar** [comment]
Ah, I just realized I have fetch.fsckObjects in my gitconfig - so that would explain.

I'm guessing this is WONTFIX then, right?

**Comment by pixelb** [comment]
Thanks for confirming your settings.
Closing this
