### ISSUE TITLE
Why not gnu-tar

### ISSUE THREAD

**Issue by ORESoftware** [coreutils/coreutils#22]
I am looking for gtar (gnu-tar?)..
tar on a mac is weird by default.
shant gnu-tar come with coreutils?
to get gtar I had to run `brew install gnu-tar` , I would have expected it to come with coreutils but idk

**Comment by bhaible** [comment]
GNU tar is a separate package, because it's quite complex of its own. We can't put all possible programs into coreutils; it would become unmaintainable.
