### ISSUE TITLE
sort -hu

### ISSUE THREAD

**Issue by b1tninja** [coreutils/coreutils#23]
https://github.com/coreutils/coreutils/blob/1c8050cc4d862a905ba4e91ac6df2f3c1e501649/src/sort.c#L2986

When using different sorting methods such as -h[uman] combined with -u[nique] not all unique values are returned. The comments seem to indicate there is an assumption about list ordering

**Comment by b1tninja** [comment]
Will email a proposed patch.... Leaving this open till then

**Comment by agordon** [comment]
With no further follow-ups (on github), I'm closing this issue.
Please send any future patches to coreutils@gnu.org .

**Comment by b1tninja** [comment]
Yeah wasn't able to figure out what was going on with the sorting but there does seem to be an issue if someone else wants to take a stab
