### ISSUE TITLE
Change case via 'mv' on case-insensitive file systems

### ISSUE THREAD

**Issue by darkdragon-001** [coreutils/coreutils#25]
There should be a possibility to change case on case-insensitive file systems:

    $ mv 'image.JPG' 'image.jpg'
    mv: 'image.JPG' and 'image.jpg' are the same file

**Comment by agordon** [comment]
Hello,
At least on MacOS's APFS filesystem, the `mv` command does exactly that.
On other filesystems results might differ. As this is an old issue, I'm closing it.
For further assistance, please DO NOT open github issues - instead send an email to coreutils@gnu.org .
