### ISSUE TITLE
suggestions: append indicator for macos alias

### ISSUE THREAD

**Issue by gMan1990** [coreutils/coreutils#27]
- file2-Hard Link, file3-Symbolic Link, file4-Alias
    - macos ls

        ```text
        > ls -lFhAi
        total 16
        64821 -rw-r--r--  2 t_liang  staff     0B 10 25 13:53 file1
        64821 -rw-r--r--  2 t_liang  staff     0B 10 25 13:53 file2
        64827 lrwxr-xr-x  1 t_liang  staff     5B 10 25 13:53 file3@ -> file1
        64828 -rw-r--r--@ 1 t_liang  staff   1.1K 10 25 13:53 file4
        ```

    - coreutils ls

        ```text
        > gls -lFhAi
        total 8.0K
        64821 -rw-r--r-- 2 t_liang staff    0 10 25 13:53 file1
        64821 -rw-r--r-- 2 t_liang staff    0 10 25 13:53 file2
        64827 lrwxr-xr-x 1 t_liang staff    5 10 25 13:53 file3 -> file1
        64828 -rw-r--r-- 1 t_liang staff 1.2K 10 25 13:53 file4
        ```

        - Q: the alias `file4` not have a indicator?

----
- `-F, --classify: append indicator (one of */=>@|) to entries`
    - Q: `*` mean?
    - Q: `/` mean?
    - Q: `=` mean?
    - Q: `>` mean?
    - Q: `@` mean?
    - Q: `|` mean?

**Comment by agordon** [comment]
Hello,
The coreutils manual clearly shows what they mean:
>  for regular files that are executable, append ‘*’ [...]  ‘/’ for directories, ‘@’ for symbolic links, ‘|’ for FIFOs, ‘=’ for sockets, ‘>’ for doors, and nothing for regular files.

https://www.gnu.org/software/coreutils/manual/html_node/General-output-formatting.html#index-_002d_002dclassify

For further questions, please do not use github - instead write to coreutils@gnu.org .
As such I'm closing this issue.
