### ISSUE TITLE
Generate Single Binary File

### ISSUE THREAD

**Issue by harshitalpha** [coreutils/coreutils#34]
Hello There,
There is one file named **gen-single-binary.sh** in **build-aux**, I think that this file can be used to generate a single binary file for all c files in **src** folder.
I tried it using the following command
`sh gen-single-binary.sh path/to/coreutils/src/local.mk`

I think this command runs successfully, as it prints 
```
Automatically generated by gen-single-binary.sh.  DO NOT EDIT BY HAND!
src_libsinglebin_dir_a_DEPENDENCIES = src/libsinglebin_ls.a
src_libsinglebin_vdir_a_DEPENDENCIES = src/libsinglebin_ls.a
src_libsinglebin_arch_a_DEPENDENCIES = src/libsinglebin_uname.a
Command arch
noinst_LIBRARIES += src/libsinglebin_arch.a
src_libsinglebin_arch_a_SOURCES = src/coreutils-arch.c
src_libsinglebin_arch_a_ldadd =  src/libsinglebin_uname.a
src_libsinglebin_arch_a_CFLAGS = "-Dmain=single_binary_main_arch (int, char **);  int single_binary_main_arch"  -Dusage=_usage_arch $(src_coreutils_CFLAGS)
.. for all c files
```

But I am not able to find out that if binary file generated where it is? If it does not generate a binary file then how to generate a single binary file of all the c program in **src** directory.

Thanks

**Comment by pixelb** [comment]
That's an internal build helper. To build the single binary version please use `./configure -enable-single-binary`.
Then make will build the `coreutils` binary, and `make install` will install the appropriate symlinks or scripts on the system

**Comment by harshitalpha** [comment]
Thanks,
But, I have some more issue, Command `./configure -enable-single-binary` it seems to run perfectly, but when I run `make` command it is throwing some error 
```
lib/acl-internal.c: In function 'free_permission_context':
lib/acl-internal.c:479:1: error: function might be candidate for attribute 'const' [-Werror=suggest-attribute=const]
 free_permission_context (struct permission_context *ctx)
 ^
cc1: all warnings being treated as errors
Makefile:9822: recipe for target 'lib/acl-internal.o' failed
make[2]: *** [lib/acl-internal.o] Error 1
make[2]: Leaving directory '/home/harshit/Desktop/Decomp_proj/coreutils/coreutils'
Makefile:12459: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/home/harshit/Desktop/Decomp_proj/coreutils/coreutils'
Makefile:6564: recipe for target 'all' failed
make: *** [all] Error 2
```

Can you tell me what am I doing wrong?

Thanks

**Comment by harshitalpha** [comment]
Thanks,
 `*.o` files are generated in the compilation process before the linking, but what I need is a final compiled binary with all the compilation process. since we have enabled `enable-single-binary` flag, we should have a single binary file generated in the repository, but I am not able to find out where the single binary file is and what's the name of the file is? It will be great if you can please help me a little bit about this.

Thanks in advance

**Comment by pixelb** [comment]
The binary is src/coreutils. As mentioned, make install will install just that and the associated symlinks or scripts.
You could test this out in a temp dir with: make DESTDIR=$PWD/testinstall install
