### ISSUE TITLE
Some problems of tests

### ISSUE THREAD

**Issue by delvershi** [coreutils/coreutils#35]
Hello,
I'm sorry to disturb you. But I have searched for a long time and have no idea.
Things are like this：
I have configured and installed coreutils:
```
./configure CC=x86_64-gentoo-linux-musl-gcc CFLAGS=-static --program-suffix=.x86 --prefix=coreutils-8.32/bin`
make
make install
```
I can find programs in the file of coreutils-8.32/bin/bin.
i have do some changes in this programs and put them in the file of coreutils-8.32/bin/after.
Now i want to compare the performance between the programs in coreutils-8.32/bin/bin and coreutils-8.32/after.
But this can't achieve by using 
```time make -j $(nproc) check SUBDIRS=.```
What should i do?
In addition,i want to compare the performance between the single program before and after changes.
so i try to use 
```make check TESTS=tests/ls/ VERBOSE=yes SUBDIRS=.```
to test all files in tests/ls,but failed. Could you tell a path to do that?

Thanks!

**Comment by pixelb** [comment]
I would manually move directories `bin` and `after` to the expected place before running the test suite

Re testing a dir, you could
```
tests="$(shopt -s nullglob; echo tests/$tests_dir/*.{sh,pl})"
make check TESTS="$tests" ...
```

**Comment by delvershi** [comment]
Sorry, i think you didn't fully understand me.
In a short, I don't want to test the performance of the coreutilies in src/.
I have put coreutils in another path,such as after:
```
after$ ls
b2sum.changed      false.changed        ls.changed      tr.changed       true.changed
...                             ...                            ...
```
So how can i test the programs in after/ by using coreutils test suit?
