### ISSUE TITLE
false.c doesn't have a license header

### ISSUE THREAD

**Issue by mmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmrn** [coreutils/coreutils#37]
Just a little consistency issue I noticed, I think this is a really major bug and needs to be fixed ASAP!

**Comment by masterneko** [comment]
I made a pull request here #39

**Comment by agordon** [comment]
Hello,
The pull-request was closed, and so I'm closing this issue as well.
Generally speaking, very small files (and also - small patches) do not require copyright (rule of thumb: less than 10 lines of code).
