### ISSUE TITLE
dd more drive info before copies

### ISSUE THREAD

**Issue by netpipe** [coreutils/coreutils#45]
would be nice if we could get more detailed drive infomation and confirmations with dd command.

would be nice to see an option to bypass the are you sure you want to copy over drive /dev/sdd (specific size and maybe the lsusb string so we know if its our drive) GB

**Comment by pixelb** [comment]
It seems like such functionality would be appropriate for another tool, which used dd underneath

**Comment by netpipe** [comment]
thats what i thought too, but thats not normally the use case. i have several GUI's for the task but it always ends up being dd that gets used.(gnome-disks crashes alot)
