### ISSUE TITLE
Wrong format for "date" program in LANG=id_ID.UTF-8

### ISSUE THREAD

**Issue by bayuah** [coreutils/coreutils#46]
I'm not sure if this is translation related issues, but each time I run the "`date`" program the format is wrong and make me confused.

**How to reproduce:**
```shell
LANG=id_ID.UTF-8 date --date="2021-01-26T18:49:57+07:00"
```
**The result**:
```
Sel 26 Jan 2021 06:49:57  WIB
```
**Expected result:**
```
Sel 26 Jan 2021 18:49:57 WIB
```
As you can see, the result is wrong. This is off by 12 hours.

It's really frustrating if unaware user use "date" as logging program and they get incorrect result.

**Additional note:**

If I use `LANG=id date`, the result is `Tue Jan 26 18:49:57 WIB 2021`. It seem the time format is correct, but the language and date format is messed up.

**NB**: I know I can use: `date +"%a %d %b %Y %T %Z"` with result `Sel 26 Jan 2021 18:49:57 WIB` to make correct date.

**Comment by bayuah** [comment]
Any way, after a few months I just fix it by myself.

I just edit `/usr/share/i18n/locales/id_ID` file and change:
- `d_t_fmt` from "%a %d %b %Y **%r**" to "%a %d %b %Y **%T**"; and
- `date_fmt` from "%a %d %b %Y **%r** %Z" to "%a %d %b %Y **%T** %Z".

Or, you can use `sed` to help you.
```
sed -i 's/d_t_fmt.*/d_t_fmt     "%a %d %b %Y %T"/' /usr/share/i18n/locales/id_ID
sed -i 's/date_fmt.*/date_fmt    "%a %d %b %Y %T %Z"/' /usr/share/i18n/locales/id_ID
```

As you can see, "`%r`" means locale's 12-hour clock time according `date` manual, and "`%R`" is 24-hour hour and minute. But I prefer "`%T`" because it is same as "`%H:%M:%S`". It looks like the original author was mixed-up.

Then I call `locale-gen` to regenerate the new format.

I hope it will help somebody that have same issue with me.

But, I still not sure where to report this and I hope somebody can help me about it.

**Comment by phmccarty** [comment]
The locale definitions are maintained in glibc, so you could [open a bug report](https://www.gnu.org/software/libc/bugs.html) with that project.

**Comment by bayuah** [comment]
Oh, thank you, @phmccarty. I'll close this and probably open said bug report there.
