### ISSUE TITLE
Unexpected behaviour of 'realpath' for option --no-symlinks

### ISSUE THREAD

**Issue by RalfNaujokat** [coreutils/coreutils#49]
Hi all,

for me it looks like realpath does not quite work as expected.

SymLinks are resolved, even though option --no-symlinks (-s) was given.
The attached *.sh file produces the following output:

<pre>

### About...

===
realpath (GNU coreutils) 8.32
Copyright (C) 2020 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <https://gnu.org/licenses/gpl.html>.
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Written by Padraig Brady.
===

Unexpected behavior for option
  -s, --strip, --no-symlinks   don't expand symlinks

### Prepare
...

### Show setup

PWD:
/tmp/realpath-err-demo

.:
total 4
lrwxrwxrwx 1 local-admin local-admin   11 Mär  4 18:07 linked-folder -> real-folder
drwxrwxr-x 2 local-admin local-admin 4096 Mär  4 18:07 real-folder

./real-folder:
total 0
lrwxrwxrwx 1 local-admin local-admin 9 Mär  4 18:07 linked-file -> real-file
-rw-rw-r-- 1 local-admin local-admin 0 Mär  4 18:07 real-file

### Start

PWD:
/tmp/realpath-err-demo/linked-folder

### Ok so far:

Expected real-folder, real-file
/tmp/realpath-err-demo/real-folder/real-file
/tmp/realpath-err-demo/real-folder/linked-not-existing

### Unexpected:

Expected linked-folder, linked-file
/tmp/realpath-err-demo/real-folder/linked-file
/tmp/realpath-err-demo/real-folder/linked-not-existing
</pre>

grretings
  Ralf

Attached *.sh script

[realpath-err-demo.sh.txt](https://github.com/coreutils/coreutils/files/6085405/realpath-err-demo.sh.txt)

**Comment by pixelb** [comment]
To summarize your issue, you are surprised -s uses the physical rather than logical current working directory.
You can see the difference with:

```
$ realpath -Lsm $(pwd -L)
/tmp/realpath-err-demo/linked-folder

$ realpath -Lsm .
/tmp/realpath-err-demo/real-folder

```

Following up the discussion here:
https://lists.gnu.org/archive/html/coreutils/2021-03/msg00001.html
Closing here so we're handling in a single place,
but feel free to comment more here if you prefer
