### ISSUE TITLE
Sort by version idiosyncrasy

### ISSUE THREAD

**Issue by birdie-github** [coreutils/coreutils#51]
I do understand that this github mirror is not a proper place for reporting bugs but I just refuse to use email do that because such a workflow IMO is absolutely inconvenient, so I'm reporting a problem here and if coreutils developers are interested they will fix it regardless.

I have coreutils 8.32 installed (to be precise `coreutils-8.32-18.fc33.x86_64`)

 It looks like sort by version doesn't always work correctly. Consider this listing:

    libpango-1.0.so
    libpango-1.0.so.0
    libpango-1.0.so.0.4800.4
    libpangocairo-1.0.so
    libpangocairo-1.0.so.0
    libpangocairo-1.0.so.0.4800.4
    libpangoft2-1.0.so
    libpangoft2-1.0.so.0
    libpangoft2-1.0.so.0.4800.4
    libpangomm-1.4.so.1
    libpangomm-1.4.so.1.0.30
    libpangoxft-1.0.so
    libpangoxft-1.0.so.0
    libpangoxft-1.0.so.0.4800.4

This is exactly what you see when you sort by name.

However when you change the sorting mode to "by version" then something weird happens:

    libpangocairo-1.0.so
    libpangocairo-1.0.so.0
    libpangocairo-1.0.so.0.4800.4
    libpangoft2-1.0.so
    libpangoft2-1.0.so.0
    libpangoft2-1.0.so.0.4800.4
    libpangomm-1.4.so.1
    libpangomm-1.4.so.1.0.30
    libpangoxft-1.0.so
    libpangoxft-1.0.so.0
    libpangoxft-1.0.so.0.4800.4
    libpango-1.0.so
    libpango-1.0.so.0
    libpango-1.0.so.0.4800.4

This doesn't look right and seems rather illogical. Why has "libpango-1.0.so" become the last one on the list?

Please fix.

**Comment by birdie-github** [comment]
@pixelb 
@eggert 

Source: https://midnight-commander.org/ticket/4234

**Comment by agordon** [comment]
Hello,
Please see detailed explanation of "version sort" in GNU coreutils here: https://www.gnu.org/software/coreutils/manual/coreutils.html#Version-sort-ordering , particularly section 30.1.3 regarding subjective "illogical" results.

While opinions may differ regarding what's "absolutely inconvenient", please DO use the coreutils@gnu.org mailing list for further questions - as that is the preferred method by the coreutils maintainers.

**Comment by birdie-github** [comment]
@agordon 

The document is quite long, what should I be looking at?
