### ISSUE TITLE
Please publish a new release

### ISSUE THREAD

**Issue by polarathene** [coreutils/coreutils#52]
As others have expressed, mailing lists are antiquated to deal with. Feel free to ignore and close this whenever it's seen.

---

The last release was March 2020 with 8.32. That is the longest duration between a release for over a decade of coreutil releases.

Not much came up searching the web, this projects README or the resource links provided in this issue template. I did come across an old mailing list question where the answer about release cadence was "whenever it's ready"..

Is there a roadmap or related resource to get an idea of what's blocking that release? (_this is a handy feature that platforms like Github or Gitlab can help with_)

---

I'm particularly interested in the [`cp --reflink=auto` default introduced back in June 2020](https://github.com/coreutils/coreutils/commit/25725f9d41735d176d73a757430739fb71c7d043) (_fun fact: it's been exactly one year since this commit was made_). Some distros backport this, but it'd be nicer to rely on an official release.

It can be confusing/unexpected to find that the behaviour differs between distros packaging for `coreutils` when the version is the same..

**Comment by pixelb** [comment]
Yes we're working on a new major release which should be ready in the next few weeks.
There are fundamental changes to cp like you referenced that are appropriate for new major release

**Comment by polarathene** [comment]
@pixelb sorry to bother you, did you run into any blockers that delayed the release? Do you have a rough idea of what is left to do?

No pressure, just hopeful a new release will be available this year for distros with slower release cycles and LTS releases to pick up before their cut off points in 2022Q1.

**Comment by pixelb** [comment]
I've actually completed the last major adjustment I wanted for coreutils 9,
and hope to release in a week or so

**Comment by pixelb** [comment]
Coreutils 9.0 is released
https://lists.gnu.org/archive/html/coreutils-announce/2021-09/msg00000.html
