### ISSUE TITLE
updated and now 'rm' does not work, command not found.

### ISSUE THREAD

**Issue by JasonUK786** [coreutils/coreutils#53]
I've just updated ubuntu with `sudo apt-get update` and `sudo apt-get upgrade -y` but now when I try using the `rm` command it says command not found. I try `sudo apt install coreutils` but it's showing I'm on the latest version.

**Comment by iamlambda** [comment]
well, if `whereis rm` doesn't give you rm's path, it means you deleted it. If so, just grab the rm file in the src directory and compile it

**Comment by alejo-ortega** [comment]
Try running `/bin/rm` insted of just, `/bin/rm` it must be some conflict with users or alias/path namings

**Comment by bayuah** [comment]
My system also Ubuntu 20.04.2 LTS. My `which rm` result is `/usr/bin/rm`. Try to check that.

Also:
```
$ ls --full-time -l /usr/bin/rm
-rwxr-xr-x 1 root root 72056 2019-09-05 17:38:40.000000000 +0700 /usr/bin/rm
```

Not change since 2019. Are you sure it is not deleted? Try `hash -r` too to refresh file path.

**Comment by pixelb** [comment]
closing this as it seems to be a local issue, rather than an upstream issue
