### ISSUE TITLE
test fiemap-2.sh or sparse-2.sh fail on BTRFS

### ISSUE THREAD

**Issue by changyp6** [coreutils/coreutils#54]
Building latest coreutils, running sparse-2.sh test on btrfs will FAIL.
After digging on the test script, and run all the test case manually, I have found the reason.
test fails on the last part, on line 58
```
  51 cp --sparse=always k k2 || fail=1
  52 if test $(stat -c %b k2) -ge $(stat -c %b k); then
  53   # If not sparse, then double check by creating with dd
  54   # as we're not guaranteed that seek will create a hole.
  55   # apfs on darwin 19.2.0 for example was seen to not to create holes < 16MiB.
  56   hole_size=$(stat -c %o k2) || framework_failure_
  57   dd if=k of=k2.dd bs=$hole_size conv=sparse || framework_failure_
  58   test $(stat -c %b k2) -eq $(stat -c %b k2.dd) || fail=1
  59 fi
```
on ext4 file system, `cp --sparse=always k k2` will create k2 smaller than k, thus skip the following tests
on btrfs file system, `cp --sparse=always k k2` will create k2 the same size of k, thus triggers the following tests in the `if` block
on line 57, however, `dd if=k of=k2.dd bs=$hole_size conv=sparse` will create `k2.dd` smaller than `k2`, which is also smaller than `k`
however, on line 58, this test expects `k2` and `k2.dd` are the same size.
I think on line 58, `-eq` should be `-ge`, because `dd if=k of=k2.dd bs=$hole_size conv=sparse` works as expected to create a file smaller than the source file.

`cp` and `dd` works differently with `--sparse` on ext4 and btrfs

**Comment by changyp6** [comment]
Because BTRFS is SSD-aware filesyste, when doing `cp --sparese=always k k2`, because `k` is not modified, and the best behavior of this `cp`  for a SSD driver is just to log `k2` is `k`, that's why `test $(stat -c %b k2) -ge $(stat -c %b k)` is `true`, which shows that `copy-on-write` of btrfs works perfectly.

**Comment by pixelb** [comment]
We're trying to correlate the behavior of cp and dd here.
I think we need to adjust the cp like:

  -cp --sparse=always k k2 || fail=1
  +cp --reflink=never --sparse=always k k2 || fail=1

I'll test out locally and submit a patch.
I'd appreciate if you could also test this adjustment. thanks

**Comment by pixelb** [comment]
I've proposed this change https://lists.gnu.org/archive/html/coreutils/2021-08/msg00014.html
I tested on a loop back btrfs file system and reproduced the issue, and confirmed the above fixes it

**Comment by changyp6** [comment]
> I've proposed this change https://lists.gnu.org/archive/html/coreutils/2021-08/msg00014.html
> I tested on a loop back btrfs file system and reproduced the issue, and confirmed the above fixes it

Thank you for your quick response!!
