### ISSUE TITLE
Command 'ls' and Wild card (?) question mark, is not displaying file names properly with 3 chars long, in bin directory

### ISSUE THREAD

**Issue by GabrielCosta-stack** [coreutils/coreutils#55]
OS Version:
Linux Mint 20.3

Coreutils package version:
8-30.3ubuntu

I am trying to list file names with exactly 3 chars using the command 'ls /bin/???' in the 'bin' directory and the result returns all directories in the 'bin' directory, when it should return only files with a size of 3 chars. 

I also noticed that the same command 'ls /bin/???' on Linux Mint in version 19.3 works perfectly, it returns only the files with a size of 3 chars in the 'bin' directory.

It should also be noted that in the user directories it also behaves as expected, returning only 3 chars.

Is this behavior expected or is it a bug? 

Thank you.

**Comment by pixelb** [comment]
It's unusual to have dirs under /bin, but from your description it seems mint 20.3 does.
I suspect adding the `-d` option to ls will stop the expansion of dir parameters.

One can check this more generally with `ls -d /lib/???`

**Comment by GabrielCosta-stack** [comment]
Thanks for the quick answer, that did the trick. 
Keep up the great work.
You are awesome.
