### ISSUE TITLE
cp --reflink=always leaves a zero-length file when failing

### ISSUE THREAD

**Issue by CorrosiveTruths** [coreutils/coreutils#56]
cp --version:
cp (GNU coreutils) 9.0
Packaged by Gentoo (9.0-r2 (p0))
Copyright (C) 2021 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <https://gnu.org/licenses/gpl.html>.
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Written by Torbjorn Granlund, David MacKenzie, and Jim Meyering.

uname -a:
Linux Portal 5.15.29-gentoo-dist #1 SMP Tue Mar 22 09:57:30 GMT 2022 x86_64 Intel(R) Core(TM) i5-4440 CPU @ 3.10GHz GenuineIntel GNU/Linux

Command used (the idea was to show you can't do cross-mount reflinking yet):
cp --reflink=always /.snapshots/3616/snapshot/root/backup.sh butts

Expected: 
cp: failed to clone 'butts' from '/.snapshots/3616/snapshot/root/backup.sh': Invalid cross-device link
And no file called 'butts'.
Actual:
cp: failed to clone 'butts' from '/.snapshots/3616/snapshot/root/backup.sh': Invalid cross-device link
And a zero-size file called 'butts'.

**Comment by pixelb** [comment]
This is awkward to handle generally as previously discussed at https://bugzilla.redhat.com/921708
I'll think a bit more about this, but closing as can't fix for now.
