### ISSUE TITLE
pathchk and _POSIX_NAME_MAX

### ISSUE THREAD

**Issue by musinsky** [coreutils/coreutils#60]
```
$ uname -a
Linux muke 5.18.10-200.fc36.x86_64 #1 SMP PREEMPT_DYNAMIC Thu Jul 7 17:21:38 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
$ rpm -qf $(which pathchk)
coreutils-9.0-5.fc36.x86_64
$ getconf -a | grep _POSIX_NAME_MAX
_POSIX_NAME_MAX                    255
```
```
$ pathchk -p aaaaaaaaaaaaaaaaaaaaaaaaa
pathchk: limit 14 exceeded by length 25 of file name component ‘aaaaaaaaaaaaaaaaaaaaaaaaa’
```
Why **pathchk** works with `_POSIX_NAME_MAX` 14 and not with 255 ?
Exist any way how **pathchk** will be works with `_POSIX_NAME_MAX=255` ?

Thanks !

**Comment by pixelb** [comment]
Well the -p is to check for portability to all systems, not just the current one.
For example the latest POSIX spec states:

"For example, {NAME_MAX} frequently changes between System V and BSD-based file systems; System V uses a maximum of 14, BSD 255. On an implementation that provides both types of file systems, an application would be forced to limit all pathname components to 14 bytes, as this would be the value specified in [<limits.h>](https://pubs.opengroup.org/onlinepubs/9699919799/basedefs/limits.h.html) on such a system."

Also on my Fedora system:

```
$ find /usr/include/ -type f | xargs grep _POSIX_NAME_MAX
/usr/include/bits/posix1_lim.h:#define	_POSIX_NAME_MAX		14
```

You can see pathconf() being called when -p is not specified:
```
$ ltrace -e pathconf pathchk -p aaaaaaaaaaaaaaa
pathchk: limit 14 exceeded by length 15 of file name component ‘aaaaaaaaaaaaaaa’

$ ltrace -e pathconf pathchk aaaaaaaaaaaaaaa
pathchk->pathconf(0x4080bb, 3, 0, 14)                                       = 255
```
