### ISSUE TITLE
files starting with "-" makes stat to say "invalid option -- 'S'"

### ISSUE THREAD

**Issue by estatistics** [coreutils/coreutils#64]
files starting with "-" makes stat to say "invalid option -- 'S'"

example, create a file "-fddsfdf.txt" and run "stat *" or "stat -fddsfdf.txt"

and then again , create a file "fddsfdf.txt" and run "stat *" or "stat fddsfdf.txt"

In first case, it will says "invalid option -- 'S'",
in second, it will be run normally. 

No LSB modules are available.
Distributor ID:	Debian
Description:	Debian GNU/Linux 11 (bullseye)
Release:	11
Codename:	bullseye

stat (GNU coreutils) 8.32
Copyright (C) 2020 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <https://gnu.org/licenses/gpl.html>.
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

**Comment by pixelb** [comment]
Responded to at https://lists.gnu.org/archive/html/bug-coreutils/2022-11/msg00018.html
