### ISSUE TITLE
Keep the git sources in a compileable variant at all times please

### ISSUE THREAD

**Issue by rubyFeedback** [coreutils/coreutils#69]
I use this issue tracker even if nobody reads it. IMO github issue trackers are so much
more convenient to use, compared to oldschool email ...

Anyway.

Today I checked out the sources here via git.

Running "./configure" does not work from the git checkout though.

My next attempt was to use "autoconf".

This failed via:

    sh: line 1: build-aux/git-version-gen: No such file or directory
    /usr/bin/m4:configure.ac:659: cannot open `m4/cu-progs.m4': No such file or directory
    autom4te: error: /usr/bin/m4 failed with exit status: 1

Would it be possible to maintain the git sources in a compileable variant at all times?
As far as I know this is the case with meson/ninja, so perhaps one could consider
abandoning GNU configure if it is such a hassle to keep the toplevel sources in a
compileable version at all times.

Note that this is the case with BOTH (!) gcc and binutils. When I do a git clone
checkout on them, I can compile both as-is, without having to do anything else,
so something is weird with coreutils. Please learn from gcc and binutils - both
projects handle this situation better, IMO.

**Comment by pixelb** [comment]
The process for our repo is use ./bootstrap before ./configure
For details please see https://github.com/coreutils/coreutils/blob/master/README-hacking
