### ISSUE TITLE
 Jan 2038... support not detected

### ISSUE THREAD

**Issue by navinagaraj** [coreutils/coreutils#70]
Trying to cross-compile a coreutils package for RPI-3 i am facing this issue. While passing the "**ac_year2038_required=no**" in the configuration option build get success is that ok? any sugession.

**Config error:**
```
checking for arm-linux-gnueabihf-ar... arm-linux-gnueabihf-ar
checking for arm-linux-gnueabihf-gcc option to enable large file support... -D_FILE_OFFSET_BITS=64
checking for arm-linux-gnueabihf-gcc option to enable timestamps after Jan 2038... support not detected
configure: error: in '/home/*/Documents/build/coreutils-9.3':
configure: error: support for timestamps after Jan 2038 is required
See 'config.log' for more details
```

**Comment by pixelb** [comment]
Since this is such an impending issue, since 9.3 one needs to explicitly state you don't care about operation beyond 2038 (including relative date operations to current date etc.). `ac_year2038_required=no` is the correct supported way to explicitly build like this (as documented in README-install)
