### ISSUE TITLE
Can print -e or -n or -E from the begining of the echo

### ISSUE THREAD

**Issue by xrbh70** [coreutils/coreutils#76]
echo "-e" or echo "-n" or echo "-E" does not print -e or -n or -E even if you put it in single quote or escape the character
the workarounf that i did it add a space into the quoutes like
echo " -e"
then it will print it
or maybe
echo " -e" |sed 's/^ //'
You will have the espected result
-e

I made a script shell that uses as parameters the -e and the -n, if you put this paraemter at the begining of the call of the progman, the -e will be deleted.
example
script.sh -e -o would get in the $ @ or $* just -o

Please **do not** send pull-requests or open new issues on Github.

Github is a downstream mirror and is not frequently monitored,
all development is coordinated upstream on GNU resources.

* Send general questions or suggestions to: coreutils@gnu.org .
* Send bugs reports to: bug-coreutils@gnu.org .

## Bug reports

Before reporting a new bug, please check the following resources:

* Coreutils FAQ: https://www.gnu.org/software/coreutils/faq/coreutils-faq.html

* Coreutils Gotchas: https://www.pixelbeat.org/docs/coreutils-gotchas.html
  contains a list of some quirks and unexpected behavior (which are often
  mistaken for bugs).

* Online Manual:
  https://www.gnu.org/software/coreutils/manual/html_node/index.html

* Search the archives for previous questions and answers:

   * Coreutils Mailing list (General usage and advice):
     https://lists.gnu.org/archive/html/coreutils/

   * Bug reports Mailing List:
     https://lists.gnu.org/archive/html/bug-coreutils/

* Open Bugs:
  https://debbugs.gnu.org/cgi/pkgreport.cgi?which=pkg&data=coreutils

* Translation related issues:
  https://translationproject.org/domain/coreutils.html

## Effective bug reports

* Include a descriptive subject line (e.g. the program with which
  you experience a problem, and what the problem is).
* Include the version of the program (e.g. the output of `PROG --version`).
* Include the operating system and the type of hardware you are using
  (e.g. the output of `uname -a`).
* Include the exact command and parameters you have used.
* Clearly explain what is the output you expected to get, and what is
  the actual result you encountered.
* Include as much information as possible to reproduce the problem.
  If the problem happens on a very large input file, try to provide
  a minimal example (a subset of the input file) that still causes the problem.
  *Do not* include attachments over 40kB.
* List policy is reply-to-all, and non-subscribers may post.
* There may be a moderation delay for a first-time post, whether or not
  you subscribe.

## Mailing List Etiquette

When sending messages to coreutils@gnu.org or bug-coreutils@gnu.org :

* Send messages as plain text.
* Do not send messages encoded as HTML nor encoded as base64 MIME nor
  included as multiple formats.
* Avoid sending large messages, such as log files, system call trace
  output, and other content resulting in messages over about 40 kB.
* Avoid sending screenshots (e.g. PNG files). When reporting errors
  you encounter on the terminal, copy and paste the text to your message.

**Comment by pixelb** [comment]
This is a known portability issue, as discussed at:
https://www.pixelbeat.org/docs/coreutils-gotchas.html#echo

I recommend you use printf instead of echo

**Comment by xrbh70** [comment]
$ cat test.sh
printf "$*"

$ ./test.sh -e -a
./test.sh: line 1: printf: -e: invalid option
printf: usage: printf [-v var] format [arguments]

Same issue can not use -e as a parameter

**Comment by pixelb** [comment]
`printf '%s\n' "$@"`

**Comment by xrbh70** [comment]
Thanks
