### ISSUE TITLE
mv from gnuutils doesnt work on a mounted file system

### ISSUE THREAD

**Issue by warkcod** [coreutils/coreutils#79]
I get the error
mv: cannot move 'filename1' to 'filename2': Function not implemented
when using mv from gnuutils on a mounted filesystem, but if i use the stock mv it works fine. I'm unsure if this issue belongs here or on the gnutils issue tracker.

[bfleischer](https://github.com/bfleischer) commented [on Apr 5, 2022](https://github.com/osxfuse/osxfuse/issues/881#issuecomment-1087857429)
Please raise this issue with the coreutils/gnulib team. It seems they are calling a file system operation that is not supported by the macFUSE file system you are using. I took a brief look at the relevant coreutils and gnulib code and I think the operation might be renameatx_np(). Looks like there have been some changes to the relevant gnulib code recently. It might be worth making sure you are already using the latest version before raising the issue.

https://github.com/osxfuse/osxfuse/issues/881

**Comment by carlocaione** [comment]
Hitting this as well

**Comment by pixelb** [comment]
I see gnulib handles ENOTSUP, it should probably handle ENOSYS as well.
I'll propose a patch upstream

**Comment by pixelb** [comment]
This should be fixed with https://github.com/coreutils/gnulib/commit/ac087d49
That will be available in the next coreutils release (possibly around Oct 2024),
or is a very simple patch that might be backported to the build used on mac
