### ISSUE TITLE
mv out of memory v9.1

### ISSUE THREAD

**Issue by patrickdk77** [coreutils/coreutils#80]
When moving a folder from one zfs dataset to another zfs dataset on the same pool, mv is giving me out of memory errors.
I have lots of available ram, free -m:
               total        used        free      shared  buff/cache   available
Mem:          128891       81197       46663          51        1029       46377
Swap:          30500           3       30497

rsync works fine.

attached is the strace output.
[mv-strace.txt](https://github.com/coreutils/coreutils/files/14379474/mv-strace.txt)

**Comment by pixelb** [comment]
This looks like the fix in coreutils 9.2 in commit 6c343a55
