### ISSUE TITLE
"FAIL: test-canonicalize" coreutils v9.5 on musl libc

### ISSUE THREAD

**Issue by iFoundSilentHouse** [coreutils/coreutils#83]
Looks like I can't access https://lists.gnu.org/archive/html/bug-coreutils in my country so I have to dublicate bug report here. Already sent to bug-coreutils@gnu.org though I don't think it'll be recieved.

```test-canonicalize.c:411: assertion 'strcmp (result1, "//") == 0' failed``` is the only error message I get. Fail was not presented with previous stable versions

**Comment by iFoundSilentHouse** [comment]
Maybe it's better to just 
```
diff --git a/gnulib-tests/test-canonicalize.c b/gnulib-tests/test-canonicalize.c
index 2c4fc23..284d459 100644
--- a/gnulib-tests/test-canonicalize.c
+++ b/gnulib-tests/test-canonicalize.c
@@ -394,7 +394,7 @@ main (void)
     ASSERT (stat ("/", &st1) == 0);
     ASSERT (stat ("//", &st2) == 0);
     bool same = psame_inode (&st1, &st2);
-#if defined __MVS__ || defined MUSL_LIBC
+#if defined __MVS__
     /* On IBM z/OS and musl libc, "/" and "//" both canonicalize to
        themselves, yet they both have st_dev == st_ino == 1.  */
     same = false;
```
?
It was just working.

**Comment by pixelb** [comment]
What version of musl are you on?

**Comment by iFoundSilentHouse** [comment]
> What version of musl are you on?

1.1.24

**Comment by pixelb** [comment]
ok forwarding to bug-gnulib.
closing here
