### ISSUE TITLE
'Linux file system id' - mentioned ins STAT, but no reference found

### ISSUE THREAD

**Issue by mabra** [coreutils/coreutils#85]
Can someone provide what STAT uses in format using qualifier "i", when ist says:
`
%i     file system ID in hex
`
BTW, it doesnt look like hex, I got, for example 32, just a number, could be octal ...
Thanks!

**Comment by pixelb** [comment]
32 is valid hex. For discussion on the meaning of this, see "fsid" at:
https://man7.org/linux/man-pages/man2/statfs.2.html#VERSIONS
That man page is already referenced from the stat(1) man page.

**Comment by mabra** [comment]
> 32 is valid hex. For discussion on the meaning of this, see "fsid" at: https://man7.org/linux/man-pages/man2/statfs.2.html#VERSIONS That man page is already referenced from the stat(1) man page.

Thanks, but not a help. No "32" in any of the lists.
