### ISSUE TITLE
`paste -d` and `tr` don’t recognise Japanese `、` whereas `seq -s` does.

### ISSUE THREAD

**Issue by nisbet-hubbard** [coreutils/coreutils#89]
`paste -d` and `tr` simply take `、` as a null string. I wondered if this is for technical reasons or a bug.

**Comment by pixelb** [comment]
Right unicode chars (ideographic comma) and not treated correctly by some coreutils at present. This is a known issue that's being worked on. Note it doesn't treat the above like the empty string, rather the representative UTF-8 encoding chars as demonstrated by:

```sh
$ seq 4 | paste -s -d$'\u3001' | od -Ax -tx1z -v
000000 31 e3 32 80 33 81 34 0a                          >1.2.3.4.<
```
