### ISSUE TITLE
INSTALL missing

### ISSUE THREAD

**Issue by shrx** [coreutils/coreutils#9]
The README file mentions this in the instructions:
> If this file came to you as part of a tar archive, then see the file INSTALL for compilation and installation instructions.

However, there is currently no INSTALL file present in the .tar.gz archives or in the latest git repository. In fact, INSTALL is removed from the repository because it is listed in the .gitignore file. Should the README file be updated?

**Comment by pixelb** [comment]
The INSTALL file is in the tarball, and it's shared between multiple projects and so is copied from gnulib as part of the bootstrap process

**Comment by PatMyron** [comment]
https://github.com/coreutils/gnulib/blob/master/doc/INSTALL

CC https://github.com/coreutils/coreutils/issues/17
