### ISSUE TITLE
Please support `--envFile` in `env`

### ISSUE THREAD

**Issue by xnox** [coreutils/coreutils#91]
On a typical Linux server there are plenty of convenient locations to set environment variables as a file.

There is /etc/environment environment.d generator, various profile, bashrc, etc. some are declarative variables only, and others maybe interpreted shell scripts. And systemd units have access to EnvironmentFile= directive.

Once one is in a restricted environment without access to any of those things the options become very restrictive.

Without shell, in kubernetes upon sharing a volume between initcontainer & main service, there really are no good options to pass environment variables that are dynamicly calculated - and yet shell is undesired in the main service. And inverse - granting init container powers to set configmap maybe undesirable either....

In such cases it would be very powerful to have `--envFile` option in `env`.

As one would be able to eliminate shell and need for docker-entrypoint.sh scripts in many production containers by instead shipping entrypoint that looks like this

`#!/usr/bin/env -S --envFile=/etc/environment nginx`

Outside of distroless production containers such an option would help easily mimic environment as it would be if executed under various other tools mentioned earlier.

There is some prior art. I have considered to use `env` + `envdir` + target binary, but directory of files, one per environment variable, is not as user friendly as a single k=v files that are favoured by most other tools today.

Would this be genuinely useful? Shall I attempt to implement this?

**Comment by pixelb** [comment]
There has been talk of this on the mailing list, though there are various considerations in how to exactly support this.
The functionality does seem useful.  Note the -S option may suffice here in many cases using
```env -S "$(cat .env)" <cmd>```

See https://news.ycombinator.com/item?id=40191510 for other options and file formats.
Also see mailing list discussions at:
https://lists.gnu.org/archive/html/coreutils/2021-10/msg00001.html
https://lists.gnu.org/archive/html/coreutils/2022-01/msg00033.html

Further discussion would be best on the coreutils@gnu.org mailing list.

cheers

**Comment by xnox** [comment]
>  `env -S "$(cat .env)" <cmd>`

True, most usecases I mentioned can be addressed by cat .env.

But that needs shell right? One of my usecases as an OCI /docker entrypoint has coreutils (restricted set), but not shell. (I know weird, but shell is considered "risky").

> See https://news.ycombinator.com/item?id=40191510 for other options and file formats. Also see mailing list discussions at: https://lists.gnu.org/archive/html/coreutils/2021-10/msg00001.html https://lists.gnu.org/archive/html/coreutils/2022-01/msg00033.html
> 
> Further discussion would be best on the [coreutils@gnu.org](mailto:coreutils@gnu.org) mailing list.

Thanks will read up on all that.

**Comment by xnox** [comment]
I like https://dotenvx.com/ and I also like https://doc.rust-lang.org/cargo/reference/profiles.html
The only "issues" i have is that they are possibly large. dotenvx binary is like 41MB. the cargo cli crate without debug symbols is 906k which might be palatable. And I think they both miss the arg splitting option `-S`.

Will ponder and prototype things, but maybe it is a request to have C implementation of dotenv with env-like -S option; or the inverse env supporting something like .env by default as previously proposed.

**Comment by xnox** [comment]
also pondering if `xargs --arg-file` can help here somehow or not.

**Comment by xnox** [comment]
I wonder if C implementation of dotenv is

```
xargs --null --arg-file .env -I{} env -i -S {} env
```

When arg-file is explicitely not null terminated =) 

With a shebang like usage likely to be....

```
#!/usr/bin/env -S xargs --null --arg-file .env -I{} env -i -S {} env
```

yeah, death.

**Comment by xnox** [comment]
I feel whatever is not addressed by "$(cat .env)" can be addressed by https://crates.io/crates/dotenv crate, it's cli feature, and stripped.
